// <auto-generated />
using System;
using Comments.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comments.Api.Migrations;

[DbContext(typeof(CommentsDbContext))]
[Migration("202603180001_InitialMySqlSchema")]
partial class InitialSqliteSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

        modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<long?>("AttachmentSizeBytes")
                    .HasColumnType("INTEGER");

                b.Property<string>("AttachmentContentType")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<string>("AttachmentFileName")
                    .HasMaxLength(260)
                    .HasColumnType("TEXT");

                b.Property<string>("AttachmentStoragePath")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("TEXT");

                b.Property<string>("HomePage")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("TEXT");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ParentId");

                b.ToTable("Comments");
            });

        modelBuilder.Entity("Comments.Domain.Entities.ProcessedMessage", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("ProcessedAtUtc")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("ProcessedMessages");
            });

        modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
            {
                b.HasOne("Comments.Domain.Entities.Comment", "Parent")
                    .WithMany("Replies")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Parent");
            });

        modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
            {
                b.Navigation("Replies");
            });
#pragma warning restore 612, 618
    }
}
