// <auto-generated />
using System;
using Comments.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comments.Api.Migrations;

[DbContext(typeof(CommentsDbContext))]
partial class CommentsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<long?>("AttachmentSizeBytes")
                    .HasColumnType("bigint");

                b.Property<string>("AttachmentContentType")
                    .HasMaxLength(128)
                    .HasColumnType("varchar(128)");

                b.Property<string>("AttachmentFileName")
                    .HasMaxLength(260)
                    .HasColumnType("varchar(260)");

                b.Property<string>("AttachmentStoragePath")
                    .HasMaxLength(512)
                    .HasColumnType("varchar(512)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)");

                b.Property<string>("HomePage")
                    .HasMaxLength(512)
                    .HasColumnType("varchar(512)");

                b.Property<Guid?>("ParentId")
                    .HasColumnType("char(36)");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("varchar(128)");

                b.HasKey("Id");

                b.HasIndex("ParentId");

                b.ToTable("Comments");
            });

        modelBuilder.Entity("Comments.Domain.Entities.ProcessedMessage", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(128)
                    .HasColumnType("varchar(128)");

                b.Property<DateTime>("ProcessedAtUtc")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.ToTable("ProcessedMessages");
            });

        modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
            {
                b.HasOne("Comments.Domain.Entities.Comment", "Parent")
                    .WithMany("Replies")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Parent");
            });

        modelBuilder.Entity("Comments.Domain.Entities.Comment", b =>
            {
                b.Navigation("Replies");
            });
#pragma warning restore 612, 618
    }
}
