services:
  comments-api:
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    build:
      context: .
      dockerfile: src/Comments.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
      Persistence__Provider: Sqlite
      ConnectionStrings__CommentsDb: Data Source=/app/data/comments.db
      RabbitMq__Enabled: 'true'
      RabbitMq__HostName: rabbitmq
      Elasticsearch__Enabled: 'true'
      Elasticsearch__Uri: http://elasticsearch:9200
    depends_on:
      rabbitmq:
        condition: service_started
      elasticsearch:
        condition: service_started
    ports:
      - '5000:5000'
    volumes:
      # Зберігає SQLite-файл між перезапусками контейнера API.
      - comments_data:/app/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - '9200:9200'

volumes:
  comments_data:
