version: '3.9'

services:
  comments-api:
    build:
      context: .
      dockerfile: src/Comments.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
      Persistence__Provider: MySql
      ConnectionStrings__CommentsDb: Server=mysql;Port=3306;Database=comments;User=comments_user;Password=comments_password;
      RabbitMq__Enabled: 'true'
      RabbitMq__Host: rabbitmq
      Elasticsearch__Enabled: 'true'
      Elasticsearch__Url: http://elasticsearch:9200
    depends_on:
      - mysql
      - rabbitmq
      - elasticsearch
    ports:
      - '5000:5000'

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: comments
      MYSQL_USER: comments_user
      MYSQL_PASSWORD: comments_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3306:3306'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - '9200:9200'
